openapi: 3.0.0
info:
  title: Galasa Web Requests
  version: 0.0.1

servers:
  - url: 'http://{server}:{port}'
    variables:
      server:
        default: localhost
      port:
        default: 8080

paths:
  /cps/{property}:
    get:
      summary: Get CPS Property
      parameters:
        - name: property
          in: path
          description: Property Name
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Value of CPS Property
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CPSResponse'
  /ras/{runName}:
    get:
      summary: Get RAS info for a test
      parameters:
        - name: runName
          in: path
          description: Run Name
          required: true
          schema:
            type: string
      responses:
        '200':
          description: RAS Info
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RASResponse'
  /runs/{id}:
    get:
      summary: Get Run Info
      parameters:
        - name: id
          in: path
          description: User ID
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Run Info
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestRuns'
    post:
      summary: Start Test Runs
      parameters:
        - name: id
          in: path
          description: User ID
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TestRunRequest'
      responses:
        '200':
          description: Test Submitted

components:
  schemas:
    CPSResponse:
      properties:
        value:
          type: string
    RASResponse:
      properties:
        runlog:
          type: string
        testStructure:
          type: any
        artifactFiles:
          type: array
          items:
            type: any
    TestRuns:
      properties:
        complete:
          type: boolean
        runs:
          type: array
          items:
            type: any
    TestRunRequest:
      properties:
        classNames:
          type: array
          items:
            type: any
        requestorType:
          type: string
        testStream:
          type: string
        obr:
          type: string
        mavenRepository:
          type: string
        sharedEnvironmentPhase:
          type: string
        sharedEnvironmentRunName:
          type: string
        overrides:
          type: any
        trace:
          type: boolean
        